#! /bin/bash

#Assignment:Lab 10
#Name:Bo Zhu
#Students Number:040-684-747
#Section Number:320
#Script Name:mycalc
#Description:add and substraction calculation

function add()
{
	((result=$1+$2))
	echo "The sum of $1 plus $2 equals $result" 
}

function substract()
{
	((result=$1-$2))
	echo "The sum of $1 substract $2 equals $result"
}

function displayMenu1()
{
	echo "C) Calculation" 
	echo "X) Exit"
}

function displayMenu2()
{
	echo "Please enter an integer number of X to exit:"
}

function displayMenu3()
{
	echo "+) Add"
	echo "-) Substract"
	echo "X) Exit"
}

function calc()
{
	if [ $2 = '+' ] 
	then
		add $1 $3
	elif [ $2 = '-' ]
	then
		substract $1 $3
	fi
}

if [ $# != 3 ]
then
	option='C'
	while [ $option != 'x' ] && [ $option != 'X' ]
	do
		displayMenu1
		read option
		if [ $option = 'c' ] || [ $option = 'C' ]	
		then
			displayMenu2
			read option
			if [ $option != 'x' ] && [ $option != 'X' ]
			then
				num1=$option
				displayMenu3		
				read option 
				if [ $option != 'x' ] && [ $option != 'X' ]
				then
					operator=$option
					displayMenu2	
					read option 
					if [ $option != 'x' ] && [ $option != 'X' ]
					then
						num2=$option
						calc $num1 $operator $num2		
					fi
				fi
			fi
		fi
	done
else
	calc $1 $2 $3
fi

